try:
    print('a')
except ValueError:
    print('b')
finally:
    print('c')
